"""校验 backend/requirements-dev.lock 与 requirements-dev.txt 保持同步。

与 tests/test_requirements_lock.py 的关系:

| 文件对 | 谁在装 | 守卫什么 |
|--------|--------|----------|
| requirements.txt → requirements.lock | 生产镜像(Dockerfile.backend, `--require-hashes`) | 线上依赖可复现 |
| requirements-dev.txt → requirements-dev.lock | CI 各 job | CI 装的就是锁定的那一套,不会因上游发新版而静默漂移 |

两份 lock 是**并列**关系,不是同一份的两个视图 ——
requirements-dev.txt 用 `-r requirements.txt` 把运行时依赖整份拉进来,
再叠 pytest / testcontainers / ruff / pytest-cov。所以:

- dev lock 的「直接依赖」有两种来源标记(`# via -r requirements-dev.txt`
  与 `# via -r requirements.txt`),两者都算直接依赖;
- 反过来,运行时 lock 那条「测试依赖不得入 lock」的断言在这里**不适用** ——
  dev lock 本来就该含它们,否则 CI 装不出 pytest。

为什么在 CI 里跑而不仅是本地:CI 用 `--require-hashes` 安装,lock 过期时
装不上会红;但那个红只说「装不上」,不说「为什么」。这条测试直接指出
「你改了 requirements-dev.txt 却没重新生成 lock」,省一轮排查。

重新生成命令见 backend/requirements-dev.lock 抬头(须在 py3.11 下)。
"""
from __future__ import annotations

import hashlib
import importlib.util
import re
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parents[1]
_REQUIREMENTS_DEV = _REPO_ROOT / "backend" / "requirements-dev.txt"
_REQUIREMENTS_RUNTIME = _REPO_ROOT / "backend" / "requirements.txt"
_LOCK = _REPO_ROOT / "backend" / "requirements-dev.lock"
_DIGEST_TOOL = _REPO_ROOT / "tools" / "dev" / "requirements_digest.py"

# 来源标记 = 直接依赖：pip-compile 用 `-r requirements-dev.txt`（相对路径），
# uv 0.12+ 带目录前缀 `-r backend/requirements-dev.txt`——按文件名子串匹配。
_VIA_MARKERS = ("requirements-dev.txt", "requirements.txt")


def _load_digest_module():
    """按路径加载工具模块(文件名带下划线但不在包里)。"""
    spec = importlib.util.spec_from_file_location("requirements_digest", _DIGEST_TOOL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _digest_of(text: str) -> str:
    entries = _load_digest_module().normalize(text)
    return hashlib.sha256("\n".join(entries).encode("utf-8")).hexdigest()


def _normalize(name: str) -> str:
    """PEP 503 规范化:大小写、-/_/. 视为等价。"""
    return re.sub(r"[-_.]+", "-", name).lower()


def _declared_in(path: Path) -> set[str]:
    """读取一份 requirements 文件里直接声明的包名(跳过 `-r` 等选项行)。"""
    names = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        names.add(_normalize(re.split(r"[<>=!~\[;]", line, maxsplit=1)[0].strip()))
    return names


def _declared_names() -> set[str]:
    """dev 清单声明的包 + 它 `-r` 进来的运行时包,都是 dev lock 的直接依赖。"""
    return _declared_in(_REQUIREMENTS_DEV) | _declared_in(_REQUIREMENTS_RUNTIME)


def _lock_direct_names() -> set[str]:
    """lock 里来源标记为任一份 requirements 的包 = 直接依赖。"""
    lines = _LOCK.read_text(encoding="utf-8").splitlines()
    direct, current = set(), None
    in_via = False
    for line in lines:
        pinned = re.match(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==", line)
        if pinned:
            current = _normalize(pinned.group(1))
            in_via = False
            continue
        stripped = line.strip()
        if stripped.startswith("# via"):
            in_via = True
            # 单行 direct 标记（`# via -r backend/requirements-dev.txt`）或
            # 多行 via 首行（`# via` 空，上游列表在续行）——direct 判定
            # 统一靠 marker 子串（含续行分支）。
            if current and any(m in stripped for m in _VIA_MARKERS):
                direct.add(current)
        elif in_via and stripped.startswith("#"):
            # 多行 via 的续行:`#   -r requirements.txt`
            if current and any(m in stripped for m in _VIA_MARKERS):
                direct.add(current)
        elif stripped and not stripped.startswith("--hash") and not stripped.startswith("#"):
            in_via = False
    return direct


# ── 摘要函数的直接单元测试 ──────────────────────────────────────────────
#
# 与运行时 lock 那份同源同逻辑,这里不重复测摘要函数本身(见
# test_requirements_lock.py);只测本文件特有的解析差异。


def test_lock_exists_and_is_hashed():
    assert _LOCK.is_file(), "缺少 backend/requirements-dev.lock"
    text = _LOCK.read_text(encoding="utf-8")
    assert "--hash=sha256:" in text, "dev lock 必须带 hash(--generate-hashes)"


def test_lock_generated_for_ci_python_version():
    """必须按 py3.11 解析 —— CI 所有 job 的 setup-python 都是 3.11。

    两种生成工具的写法都要认:
      pip-compile 写 `# This file was autogenerated ... with Python 3.11`
      uv          写 `#    uv pip compile --python-version 3.11 ...`
    跨版本解析出的 wheel 组合可能在 3.11 环境装不上,这条守住生成命令本身。
    """
    head_lines = []
    for line in _LOCK.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#"):
            break
        head_lines.append(line)
    head = "\n".join(head_lines)
    assert re.search(r"(with Python 3\.11|--python-version 3\.11)", head), (
        "requirements-dev.lock 不是按 Python 3.11 解析的(抬头里既没有 "
        "`with Python 3.11` 也没有 `--python-version 3.11`)。"
        "重新生成命令见该文件抬头。"
    )


def test_lock_digest_matches_requirements():
    """lock 抬头记录的摘要必须与 requirements-dev.txt 当前内容一致。

    这条最要紧:按包名的集合比对看不见版本与 extras 的漂移(`ruff>=0.16`
    改 `ruff==999`、或 extras 丢失),包名都没变而 CI 已经装到别的版本。
    """
    import subprocess
    import sys

    result = subprocess.run(
        [
            sys.executable,
            str(_DIGEST_TOOL),
            str(_REQUIREMENTS_DEV),
            str(_LOCK),
            "--check",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_lock_covers_every_declared_requirement():
    """两份 requirements 里声明的包都必须出现在 dev lock 中。

    抓的是「加了依赖但没重新生成 lock」——那样 CI 用 --require-hashes 安装
    会失败,但报错只说装不上,不说是哪个包漏了。
    """
    missing = sorted(_declared_names() - _lock_direct_names())
    assert not missing, (
        "以下依赖已声明,但 backend/requirements-dev.lock 里没有对应条目:\n  "
        + "\n  ".join(missing)
        + "\ndev lock 已过期,请按该文件抬头的命令重新生成。"
    )


def test_lock_has_no_stale_direct_requirements():
    """反向:lock 标为直接依赖、但两份 requirements 都已经删掉的包。"""
    stale = sorted(_lock_direct_names() - _declared_names())
    assert not stale, (
        "以下包在 dev lock 里标为直接依赖,但已不再声明:\n  "
        + "\n  ".join(stale)
        + "\ndev lock 已过期,请重新生成。"
    )


def test_dev_lock_supersedes_runtime_requirements():
    """dev lock 必须覆盖全部运行时依赖。

    requirements-dev.txt 靠 `-r requirements.txt` 拉运行时依赖;若哪天这一行
    被误删,上面的集合比对会因为「dev 声明⊆lock」而全绿,而 CI 将装不出
    FastAPI 等运行时包。这条直接钉住包含关系。
    """
    runtime = _declared_in(_REQUIREMENTS_RUNTIME)
    assert runtime, "requirements.txt 解析出 0 个包 —— 解析逻辑或文件本身出问题了"
    missing = sorted(runtime - _lock_direct_names())
    assert not missing, (
        "以下运行时依赖不在 dev lock 中(requirements-dev.txt 的 `-r requirements.txt`"
        "可能被删):\n  " + "\n  ".join(missing)
    )


@pytest.mark.parametrize("pkg", ["pytest", "pytest-cov", "testcontainers", "ruff"])
def test_dev_only_deps_are_present(pkg: str):
    """CI 用的 dev 依赖必须在 lock 里 —— 与运行时 lock 那条断言方向相反。

    运行时 lock 断言它们**不得**出现(否则会打进生产镜像);
    dev lock 反过来断言它们**必须**出现(否则 CI 装不出测试工具链)。
    """
    assert _normalize(pkg) in _lock_direct_names(), (
        f"{pkg} 是 CI 依赖,必须出现在 requirements-dev.txt 并进入 dev lock;"
        " 缺失说明 lock 已过期。"
    )
