#!/usr/bin/env bash
# 重新生成一份 lock（uv，按 py3.11 解析），保留文件头部的文档说明，并打摘要。
#
# 用法:
#   scripts/ci/regenerate-lock.sh <requirements> <lock> [--upgrade]
#
#   scripts/ci/regenerate-lock.sh backend/requirements.txt      backend/requirements.lock
#   scripts/ci/regenerate-lock.sh backend/requirements-dev.txt  backend/requirements-dev.lock
#
# --upgrade 的语义（重要，别默认加）：
#   uv 与 pip-tools 一样，会**沿用输出文件里已有的 pin**，只在必要时才动。
#   不加 --upgrade：改动最小、可预测 —— Dependabot 改了一个包就只动那一个包，
#     这正是自动补 lock 想要的（否则每次都会把区间内所有包刷到最新，
#     diff 巨大且不可预测）。
#   加 --upgrade：全新解析，把区间内所有包提到最新。只用于**有意的对齐**
#     （例：让生产镜像追上 CI 一直在测的版本），会一次性改动多个包。
#
# 由 .github/workflows/regenerate-locks.yml 调用（Dependabot 只改 manifest
# 不改 lock 时补上锁变更）。本地要重生成 lock 也可以直接用这个脚本，命令与
# 各 lock 抬头的文档一致。
#
# 三个非显然的点，改这个脚本前先读：
#
# 1) 必须**保留文档头部**。uv 会覆盖整个文件头部，不处理的话 lock 顶上那段
#    （生成命令、为什么用 uv、--stamp 要求）会被冲掉 —— 2026-08-30 就丢过
#    一次 26 行，另一次是 31 行。
#
# 2) 头部切断用**标记行定位**，不是行前缀过滤。后者扛不住拼接漏换行产生的
#    `## This file was autogenerated ...`（漏网会重生成出两份 uv 头部）。
#
# 3) --stamp 必须在装回头部**之后**跑。requirements_digest.py 的 read_recorded()
#    遇到第一个包行就停，摘要得落在头部注释区里。
set -euo pipefail

REQUIREMENTS="${1:?usage: regenerate-lock.sh <requirements> <lock> [--upgrade]}"
LOCK="${2:?usage: regenerate-lock.sh <requirements> <lock> [--upgrade]}"
UPGRADE="${3:-}"
[[ "$UPGRADE" == "--upgrade" || -z "$UPGRADE" ]] || {
  echo "未知参数: $UPGRADE（只支持 --upgrade）" >&2
  exit 2
}

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# ① 保存原文档头部（去掉 uv 自带的 autogen 块 —— 新文件会带自己的）
python3 - "$LOCK" <<'PY'
import pathlib
import sys

lock = pathlib.Path(sys.argv[1])
head = []
for line in lock.read_text(encoding="utf-8").splitlines():
    if line.strip() and not line.startswith("#"):
        break
    head.append(line)

# uv 的 autogen 块永远是头部的最后一段，按标记行切断丢弃。
cut = next(
    (i for i, line in enumerate(head) if "This file was autogenerated" in line),
    len(head),
)
keep = head[:cut]
# 去掉尾部空注释行，避免每次往返多堆一行
while keep and keep[-1].strip() in ("", "#"):
    keep.pop()

pathlib.Path("/tmp/lock-header.txt").write_text(
    "\n".join(keep) + "\n" if keep else "", encoding="utf-8"
)
print(f"  保存文档头部 {len(keep)} 行（原 {len(head)} 行，丢弃 uv autogen {len(head) - len(keep)} 行）")
PY

# ② 重新生成。**从仓库根运行** —— 路径写法决定 `# via` 来源标记是否带
#    `backend/` 前缀；两份 lock 统一用带前缀的形态，与各自抬头的命令一致。
if [[ "$UPGRADE" == "--upgrade" ]]; then
  echo "  重新生成 $LOCK（uv，按 py3.11 解析，--upgrade 全新解析）"
else
  echo "  重新生成 $LOCK（uv，按 py3.11 解析，沿用已有 pin）"
fi
uv pip compile --python-version 3.11 --generate-hashes --strip-extras \
  $UPGRADE --output-file "$LOCK" "$REQUIREMENTS"

# ③ 装回文档头部。补一个空注释行做分隔 —— 否则文档最后一行会紧贴
#    `# This file was autogenerated ...`，读起来像同一段。
python3 - "$LOCK" <<'PY'
import pathlib
import sys

lock = pathlib.Path(sys.argv[1])
header = pathlib.Path("/tmp/lock-header.txt").read_text(encoding="utf-8")
if header:
    if not header.endswith("#\n"):
        header += "#\n"
    lock.write_text(header + lock.read_text(encoding="utf-8"), encoding="utf-8")
PY

# ④ 打摘要（位置必须在头部注释区内，见文件头注释第 3 点）
python3 tools/dev/requirements_digest.py "$REQUIREMENTS" "$LOCK" --stamp

echo "  完成：$LOCK"
