"""add device monitoring fields

Revision ID: 001_add_device_monitoring
Revises:
Create Date: 2026-01-24 11:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001_add_device_monitoring'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('adb_state', sa.String(length=32), nullable=True))
    op.add_column('devices', sa.Column('adb_connected', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('battery_level', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('battery_temp', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('temperature', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('wifi_rssi', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('wifi_ssid', sa.String(length=128), nullable=True))
    op.add_column('devices', sa.Column('cpu_usage', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('mem_total', sa.BigInteger(), nullable=True))
    op.add_column('devices', sa.Column('mem_used', sa.BigInteger(), nullable=True))
    op.add_column('devices', sa.Column('disk_total', sa.BigInteger(), nullable=True))
    op.add_column('devices', sa.Column('disk_used', sa.BigInteger(), nullable=True))
    op.add_column('devices', sa.Column('hardware_updated_at', sa.DateTime(), nullable=True))
    op.create_index('ix_devices_host_last_seen', 'devices', ['host_id', 'last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_host_last_seen', table_name='devices')
    op.drop_column('devices', 'hardware_updated_at')
    op.drop_column('devices', 'disk_used')
    op.drop_column('devices', 'disk_total')
    op.drop_column('devices', 'mem_used')
    op.drop_column('devices', 'mem_total')
    op.drop_column('devices', 'cpu_usage')
    op.drop_column('devices', 'wifi_ssid')
    op.drop_column('devices', 'wifi_rssi')
    op.drop_column('devices', 'temperature')
    op.drop_column('devices', 'battery_temp')
    op.drop_column('devices', 'battery_level')
    op.drop_column('devices', 'adb_connected')
    op.drop_column('devices', 'adb_state')
    # ### end Alembic commands ###
