from datetime import datetime, timedelta, timezone
import logging
import os
import uuid
from typing import Any, Dict, List

from fastapi import APIRouter, Depends
from sqlalchemy import or_
from sqlalchemy.orm import Session

from backend.core.database import get_db
from backend.models.host import Host, Device
from backend.api.schemas import HeartbeatIn
from backend.api.routes.auth import verify_agent_secret

router = APIRouter(prefix="/api/v1", tags=["heartbeat"])
logger = logging.getLogger(__name__)

# 心跳快照降采样间隔（秒）：减少数据库写入压力
SNAPSHOT_INTERVAL_SECONDS = int(os.getenv("DEVICE_SNAPSHOT_INTERVAL", "30"))


def _is_auto_register_sentinel(host_id: str) -> bool:
    """兼容旧 agent 的 host_id=0 自动注册哨兵值。"""
    return str(host_id).strip() == "0"


def _allocate_host_id() -> str:
    """为自动注册主机生成新的唯一 Host ID。"""
    return f"auto-{uuid.uuid4().hex[:12]}"


def _sync_host_identity(host: Host, host_info: Dict[str, Any]) -> None:
    """根据 agent 上报的主机信息刷新展示字段，避免页面显示旧 IP。"""
    ip = (host_info or {}).get("ip")
    if not ip:
        return

    previous_ip = host.ip or host.ip_address

    host.ip = ip
    host.ip_address = ip

    autogenerated_names = {
        None,
        "",
        previous_ip,
        f"Host-{host.id}",
        f"unknown-{host.id}",
    }
    if host.name in autogenerated_names:
        host.name = ip
    if host.hostname in autogenerated_names:
        host.hostname = ip


def _update_if_not_none(device: Device, field: str, value) -> bool:
    """Helper to update device field only if value is not None"""
    if value is None:
        return False
    setattr(device, field, value)
    return True


_DEVICE_OFFLINE_TIMEOUT = int(os.getenv("DEVICE_OFFLINE_TIMEOUT", "60"))


def _mark_missing_devices_offline(
    db: Session, host_id: str, seen_serials: set, timeout: int = _DEVICE_OFFLINE_TIMEOUT
) -> List[Device]:
    """Mark devices not seen in current heartbeat as offline"""
    offline_threshold = datetime.now(timezone.utc) - timedelta(seconds=timeout)
    missing_devices = (
        db.query(Device)
        .filter(
            Device.host_id == host_id,
            or_(Device.last_seen.is_(None), Device.last_seen < offline_threshold),
        )
        .all()
    )
    changed_devices = []
    for device in missing_devices:
        if device.serial not in seen_serials:
            already_offline = (
                device.status == "OFFLINE"
                and device.adb_connected is False
                and device.adb_state == "offline"
            )
            if already_offline:
                continue

            device.status = "OFFLINE"
            device.adb_connected = False
            device.adb_state = "offline"
            changed_devices.append(device)
            # Dispatch DEVICE_OFFLINE notification
            from backend.services.notification_service import dispatch_notification_async
            dispatch_notification_async("DEVICE_OFFLINE", {
                "device_serial": device.serial,
                "device_id": device.id,
                "host_id": host_id,
            })
    return changed_devices


@router.post("/heartbeat")
async def heartbeat(payload: HeartbeatIn, db: Session = Depends(get_db), _: bool = Depends(verify_agent_secret)):
    host_info = payload.host or {}
    ip = host_info.get("ip")
    is_auto_register = _is_auto_register_sentinel(payload.host_id)

    # 旧版 agent 会用 host_id=0 触发自动注册。这里不能先按主键查 0，
    # 否则多台主机会被折叠到同一个 Host 记录里。
    host = None if is_auto_register else db.get(Host, payload.host_id)

    # Auto-create host if not exists (for testing)
    if not host:
        if ip:
            host = (
                db.query(Host)
                .filter((Host.ip == ip) | (Host.ip_address == ip))
                .first()
            )

        if not host:
            host_id = _allocate_host_id() if is_auto_register else str(payload.host_id)
            host_name = ip or f"Host-{host_id}"

            host = Host(
                id=host_id,
                hostname=host_name,
                name=host_name,
                ip=ip or f"unknown-{host_id}",
                ip_address=ip,
                status=payload.status,
                ssh_port=22,
            )
            db.add(host)
            db.flush()

    _sync_host_identity(host, host_info)

    # Update host status
    tool_catalog_outdated = (
        bool(payload.tool_catalog_version)
        and bool(host.tool_catalog_version)
        and host.tool_catalog_version != payload.tool_catalog_version
    )
    script_catalog_outdated = (
        bool(payload.script_catalog_version)
        and bool(host.script_catalog_version)
        and host.script_catalog_version != payload.script_catalog_version
    )

    host.status = payload.status
    now = datetime.now(timezone.utc)
    host.last_heartbeat = now
    host.mount_status = payload.mount_status
    if payload.tool_catalog_version:
        host.tool_catalog_version = payload.tool_catalog_version
    if payload.script_catalog_version:
        host.script_catalog_version = payload.script_catalog_version

    # ADR-0019 Phase 1: store agent-reported capacity
    capacity = payload.capacity or {}
    m = capacity.get("max_concurrent_jobs")
    if isinstance(m, int) and m > 0:
        host.max_concurrent_jobs = m

    # ADR-0019 Phase 3a: store agent identity on host
    if payload.boot_id:
        host.boot_id = payload.boot_id
    if payload.agent_instance_id:
        host.last_agent_instance_id = payload.agent_instance_id

    # Merge extra data without losing system stats
    host_extra = {}
    if payload.extra:
        host_extra.update(payload.extra)
    if payload.host:
        host_extra["host"] = payload.host
    host.extra = host_extra

    # Process devices array
    devices_data = getattr(payload, "devices", None) or []
    seen_serials = set()
    online_healthy_count = 0  # ADR-0019 Phase 1
    ws_device_updates: List[Dict[str, Any]] = []

    if devices_data:
        # Batch query existing devices to avoid N+1
        serials = [d.get("serial") for d in devices_data if d.get("serial")]
        existing_devices = {}
        if serials:
            for device in (
                db.query(Device).filter(Device.serial.in_(serials)).all()
            ):
                existing_devices[device.serial] = device

        now = datetime.now(timezone.utc)

        for dev_data in devices_data:
            serial = dev_data.get("serial")
            if not serial:
                continue

            seen_serials.add(serial)

            device = existing_devices.get(serial)

            if not device:
                device = Device(
                    serial=serial,
                    host_id=host.id,
                    model=dev_data.get("model"),
                )
                db.add(device)
                db.flush()
                existing_devices[serial] = device

            device.host_id = host.id
            if dev_data.get("model") is not None:
                device.model = dev_data.get("model")

            # Update ADB connection state
            device.adb_state = dev_data.get("adb_state", "unknown")
            device.adb_connected = bool(dev_data.get("adb_connected", False))

            # ADR-0019 Phase 1: count online healthy devices
            if (device.adb_connected is True
                    and device.adb_state not in ("offline", "unknown", "")):
                online_healthy_count += 1

            logger.info(f"device_adb_update: serial={serial}, adb_state={device.adb_state}, adb_connected={device.adb_connected}, network_latency={dev_data.get('network_latency')}")

            # Update hardware info
            hardware_updated = False
            hardware_updated |= _update_if_not_none(device, "battery_level", dev_data.get("battery_level"))
            hardware_updated |= _update_if_not_none(device, "battery_temp", dev_data.get("battery_temp"))
            hardware_updated |= _update_if_not_none(device, "temperature", dev_data.get("temperature"))
            hardware_updated |= _update_if_not_none(device, "wifi_rssi", dev_data.get("wifi_rssi"))
            hardware_updated |= _update_if_not_none(device, "wifi_ssid", dev_data.get("wifi_ssid"))
            hardware_updated |= _update_if_not_none(device, "network_latency", dev_data.get("network_latency"))
            _update_if_not_none(device, "build_display_id", dev_data.get("build_display_id"))
            if hardware_updated:
                device.hardware_updated_at = now

            # Update system resources
            _update_if_not_none(device, "cpu_usage", dev_data.get("cpu_usage"))
            _update_if_not_none(device, "mem_total", dev_data.get("mem_total"))
            _update_if_not_none(device, "mem_used", dev_data.get("mem_used"))
            _update_if_not_none(device, "disk_total", dev_data.get("disk_total"))
            _update_if_not_none(device, "disk_used", dev_data.get("disk_used"))

            # Update last_seen
            device.last_seen = now

            # Business status: based on ADB connection and lock
            if not device.adb_connected:
                device.status = "OFFLINE"
                logger.info(f"device_status_offline: serial={serial}, reason=adb_connected_false")
            elif device.lock_run_id:
                device.status = "BUSY"
                logger.info(f"device_status_busy: serial={serial}, lock_run_id={device.lock_run_id}")
            else:
                device.status = "ONLINE"
                logger.info(f"device_status_online: serial={serial}, adb_connected=true, no_lock")

            ws_device_updates.append(
                {
                    "serial": device.serial,
                    "status": device.status,
                    "battery_level": device.battery_level,
                    "temperature": device.temperature,
                    "network_latency": device.network_latency,
                    "adb_state": device.adb_state,
                    "adb_connected": device.adb_connected,
                    "host_id": device.host_id,
                    "last_seen": device.last_seen.isoformat() if device.last_seen else None,
                }
            )

    # Mark missing devices as offline
    missing_devices = _mark_missing_devices_offline(db, host.id, seen_serials)
    for device in missing_devices:
        if device.serial in seen_serials:
            continue
        ws_device_updates.append(
            {
                "serial": device.serial,
                "status": device.status,
                "battery_level": device.battery_level,
                "temperature": device.temperature,
                "network_latency": device.network_latency,
                "adb_state": device.adb_state,
                "adb_connected": device.adb_connected,
                "host_id": device.host_id,
                "last_seen": device.last_seen.isoformat() if device.last_seen else None,
            }
        )

    db.commit()

    if ws_device_updates:
        try:
            from backend.realtime.socketio_server import broadcast_device_update

            for update in ws_device_updates:
                await broadcast_device_update(update)
        except Exception as exc:
            logger.warning(f"device_update_broadcast_failed: {exc}")

    return {
        "ok": True,
        "host_id": host.id,
        "devices_count": len(seen_serials),
        "tool_catalog_outdated": tool_catalog_outdated,
        "script_catalog_outdated": script_catalog_outdated,
        # ADR-0019 Phase 1
        "capacity": {
            "max_concurrent_jobs": host.max_concurrent_jobs,
            "online_healthy_devices": online_healthy_count,
        },
    }
