import asyncio
from datetime import datetime, timedelta, timezone
import logging
import os
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, Depends
from sqlalchemy import or_
from sqlalchemy.orm import Session

from backend.core.database import get_db
from backend.core.host_identity import allocate_host_id
from backend.models.host import Host, Device
from backend.models.device_lease import DeviceLease
from backend.models.enums import LeaseStatus
from backend.core.metrics import (
    record_agent_outbox_pending,
    record_host_operation_concurrency,
)
from backend.api.schemas import HeartbeatIn
from backend.api.routes.auth import verify_agent_secret

router = APIRouter(prefix="/api/v1", tags=["heartbeat"])
logger = logging.getLogger(__name__)

# 心跳快照降采样间隔（秒）：减少硬件字段数据库写入压力
SNAPSHOT_INTERVAL_SECONDS = int(os.getenv("DEVICE_SNAPSHOT_INTERVAL", "30"))
# 建议 Agent 心跳周期（秒）；随在线设备数缓增，闭环 backpressure
HEARTBEAT_INTERVAL_MIN = int(os.getenv("STP_HEARTBEAT_INTERVAL_MIN", "15"))
HEARTBEAT_INTERVAL_MAX = int(os.getenv("STP_HEARTBEAT_INTERVAL_MAX", "60"))
HEARTBEAT_INTERVAL_BASE = int(os.getenv("STP_HEARTBEAT_INTERVAL_BASE", "20"))
# ADR-0026 P2-2: 建议每 host 日志行速率上限（lines/s）；随设备数收紧
LOG_RATE_LIMIT_BASE = int(os.getenv("STP_LOG_RATE_LIMIT_BASE", "200"))
LOG_RATE_LIMIT_MIN = int(os.getenv("STP_LOG_RATE_LIMIT_MIN", "20"))


def _suggested_heartbeat_interval(online_healthy: int) -> int:
    """Scale poll interval with fleet size (ADR-0026 P0 heartbeat 减负)."""
    # ~+1s per 10 healthy devices, clamped.
    scaled = HEARTBEAT_INTERVAL_BASE + max(0, online_healthy) // 10
    return max(HEARTBEAT_INTERVAL_MIN, min(HEARTBEAT_INTERVAL_MAX, scaled))


def _suggested_log_rate_limit(online_healthy: int) -> int:
    """Tighten per-host step_log rate as fleet grows (ADR-0026 P2-2)."""
    # -10 lines/s per 10 healthy devices, floor at LOG_RATE_LIMIT_MIN.
    scaled = LOG_RATE_LIMIT_BASE - (max(0, online_healthy) // 10) * 10
    return max(LOG_RATE_LIMIT_MIN, scaled)


def _should_write_hardware_snapshot(device: Device, now: datetime) -> bool:
    """True when hardware metrics may be persisted (downsampling gate)."""
    prev = device.hardware_updated_at
    if prev is None:
        return True
    if prev.tzinfo is None:
        prev = prev.replace(tzinfo=timezone.utc)
    return (now - prev).total_seconds() >= SNAPSHOT_INTERVAL_SECONDS


def _is_auto_register_sentinel(host_id: str) -> bool:
    """兼容旧 agent 的 host_id=0 自动注册哨兵值。"""
    return str(host_id).strip() == "0"


def _allocate_host_id(ip: Optional[str], db: Session) -> str:
    """为自动注册主机生成可读 Host ID（IPv4 → 点转横杠，如 172-21-9-6）。"""
    return allocate_host_id(
        ip,
        exists=lambda candidate: db.get(Host, candidate) is not None,
    )


def _sync_host_identity(host: Host, host_info: Dict[str, Any]) -> None:
    """根据 agent 上报的主机信息刷新展示字段，避免页面显示旧 IP。"""
    ip = (host_info or {}).get("ip")
    if not ip:
        return

    previous_ip = host.ip or host.ip_address

    host.ip = ip
    host.ip_address = ip

    autogenerated_names = {
        None,
        "",
        previous_ip,
        f"Host-{host.id}",
        f"unknown-{host.id}",
    }
    if host.name in autogenerated_names:
        host.name = ip
    if host.hostname in autogenerated_names:
        host.hostname = ip


def _update_if_not_none(device: Device, field: str, value) -> bool:
    """Helper to update device field only if value is not None"""
    if value is None:
        return False
    setattr(device, field, value)
    return True


_DEVICE_OFFLINE_TIMEOUT = int(os.getenv("DEVICE_OFFLINE_TIMEOUT", "60"))


def _mark_missing_devices_offline(
    db: Session, host_id: str, seen_serials: set, timeout: int = _DEVICE_OFFLINE_TIMEOUT
) -> List[Device]:
    """Mark devices not seen in current heartbeat as offline"""
    offline_threshold = datetime.now(timezone.utc) - timedelta(seconds=timeout)
    missing_devices = (
        db.query(Device)
        .filter(
            Device.host_id == host_id,
            or_(Device.last_seen.is_(None), Device.last_seen < offline_threshold),
        )
        .all()
    )
    changed_devices = []
    for device in missing_devices:
        if device.serial not in seen_serials:
            already_offline = (
                device.status == "OFFLINE"
                and device.adb_connected is False
                and device.adb_state == "offline"
            )
            if already_offline:
                continue

            device.status = "OFFLINE"
            device.adb_connected = False
            device.adb_state = "offline"
            changed_devices.append(device)
            # Dispatch DEVICE_OFFLINE notification
            from backend.services.notification_service import dispatch_notification_async
            dispatch_notification_async("DEVICE_OFFLINE", {
                "device_serial": device.serial,
                "device_id": device.id,
                "host_id": host_id,
            })
    return changed_devices


@router.post("/heartbeat")
async def heartbeat(
    payload: HeartbeatIn,
    db: Session = Depends(get_db),
    _: bool = Depends(verify_agent_secret),
):
    response, ws_device_updates = await asyncio.to_thread(
        _process_heartbeat_with_db, payload, db
    )

    if ws_device_updates:
        try:
            from backend.realtime.socketio_server import broadcast_device_update

            for update in ws_device_updates:
                await broadcast_device_update(update)
        except Exception as exc:
            logger.warning(f"device_update_broadcast_failed: {exc}")

    return response


def _process_heartbeat_with_db(
    payload: HeartbeatIn,
    db: Session,
) -> tuple[dict, List[Dict[str, Any]]]:
    host_info = payload.host or {}
    ip = host_info.get("ip")
    is_auto_register = _is_auto_register_sentinel(payload.host_id)

    # 旧版 agent 会用 host_id=0 触发自动注册。这里不能先按主键查 0，
    # 否则多台主机会被折叠到同一个 Host 记录里。
    host = None if is_auto_register else db.get(Host, payload.host_id)

    # Auto-create host if not exists (for testing)
    if not host:
        if ip:
            host = (
                db.query(Host)
                .filter((Host.ip == ip) | (Host.ip_address == ip))
                .first()
            )

        if not host:
            host_id = _allocate_host_id(ip, db) if is_auto_register else str(payload.host_id)
            host_name = ip or f"Host-{host_id}"

            host = Host(
                id=host_id,
                hostname=host_name,
                name=host_name,
                ip=ip or f"unknown-{host_id}",
                ip_address=ip,
                status=payload.status,
                ssh_port=22,
            )
            db.add(host)
            db.flush()

    _sync_host_identity(host, host_info)

    # Update host status
    script_catalog_outdated = (
        bool(payload.script_catalog_version)
        and bool(host.script_catalog_version)
        and host.script_catalog_version != payload.script_catalog_version
    )

    host.status = payload.status
    now = datetime.now(timezone.utc)
    host.last_heartbeat = now
    host.mount_status = payload.mount_status
    if payload.script_catalog_version:
        host.script_catalog_version = payload.script_catalog_version

    # ADR-0019 Phase 3a: store agent identity on host
    if payload.boot_id:
        host.boot_id = payload.boot_id
    if payload.agent_instance_id:
        host.last_agent_instance_id = payload.agent_instance_id

    # Merge extra data without losing system stats
    host_extra = {}
    # Preserve agent_version / install flags across extra rebuild
    prev_extra = host.extra or {}
    for keep_key in (
        "agent_version",
        "agent_installed",
        "agent_installed_at",
        "agent_code_revision",
        "agent_code_deployed",
        "agent_code_deployed_at",
    ):
        if keep_key in prev_extra:
            host_extra[keep_key] = prev_extra[keep_key]
    if payload.extra:
        host_extra.update(payload.extra)
    if payload.host:
        host_extra["host"] = payload.host
    # ADR-0019 Phase 3c: 规范化 capacity / health 存储到 extra
    if payload.capacity:
        host_extra["capacity"] = payload.capacity
    if payload.health:
        host_extra["health"] = payload.health
    # ADR-0020: persist agent_version from heartbeat payload
    if payload.agent_version:
        host_extra["agent_version"] = payload.agent_version
    if payload.agent_code_revision:
        host_extra["agent_code_revision"] = payload.agent_code_revision
    # 心跳即证明 Agent 已安装（与 ONLINE/OFFLINE 正交的安装态信号）
    host_extra["agent_installed"] = True
    if not host_extra.get("agent_installed_at"):
        host_extra["agent_installed_at"] = now.isoformat()
    host.extra = host_extra

    extra = payload.extra or {}
    if "terminal_outbox_pending" in extra:
        try:
            record_agent_outbox_pending(
                host.id, "terminal", int(extra["terminal_outbox_pending"]),
            )
        except (TypeError, ValueError):
            pass
    if "log_signal_outbox_pending" in extra:
        try:
            record_agent_outbox_pending(
                host.id, "log_signal", int(extra["log_signal_outbox_pending"]),
            )
        except (TypeError, ValueError):
            pass

    # ADR-0026 P0: per-host OperationScheduler concurrency (Agent-reported).
    ops = extra.get("operations") if isinstance(extra, dict) else None
    if isinstance(ops, dict):
        try:
            record_host_operation_concurrency(
                host.id,
                held=int(ops.get("held", 0) or 0),
                max_slots=int(ops.get("max", 0) or 0),
                waiting=int(ops.get("waiting", 0) or 0),
            )
        except (TypeError, ValueError):
            pass

    # Process devices array
    devices_data = getattr(payload, "devices", None) or []
    seen_serials = set()
    online_healthy_count = 0  # ADR-0019 Phase 1
    ws_device_updates: List[Dict[str, Any]] = []

    if devices_data:
        # Batch query existing devices to avoid N+1
        serials = [d.get("serial") for d in devices_data if d.get("serial")]
        existing_devices = {}
        if serials:
            for device in (
                db.query(Device).filter(Device.serial.in_(serials)).all()
            ):
                existing_devices[device.serial] = device

        now = datetime.now(timezone.utc)

        # Phase 6c: pre-compute busy device IDs from device_leases (replaces lock_run_id)
        existing_device_ids = [d.id for d in existing_devices.values() if d.id]
        busy_device_ids: set[int] = set()
        active_lease_host_by_device: dict[int, str] = {}
        if existing_device_ids:
            active_leases = db.query(
                DeviceLease.device_id, DeviceLease.host_id,
            ).filter(
                DeviceLease.device_id.in_(existing_device_ids),
                DeviceLease.status == LeaseStatus.ACTIVE.value,
            ).all()
            busy_device_ids = {row.device_id for row in active_leases}
            active_lease_host_by_device = {
                row.device_id: row.host_id for row in active_leases
            }

        for dev_data in devices_data:
            serial = dev_data.get("serial")
            if not serial:
                continue

            seen_serials.add(serial)

            device = existing_devices.get(serial)

            if not device:
                device = Device(
                    serial=serial,
                    host_id=host.id,
                    model=dev_data.get("model"),
                )
                db.add(device)
                db.flush()
                existing_devices[serial] = device

            lease_host = active_lease_host_by_device.get(device.id)
            if lease_host is not None and lease_host != host.id:
                logger.warning(
                    "device_host_reassignment_blocked serial=%s device=%s "
                    "reported_host=%s lease_host=%s",
                    serial, device.id, host.id, lease_host,
                )
                continue

            device.host_id = host.id
            if dev_data.get("model") is not None:
                device.model = dev_data.get("model")

            # Update ADB connection state
            device.adb_state = dev_data.get("adb_state", "unknown")
            device.adb_connected = bool(dev_data.get("adb_connected", False))

            # ADR-0019 Phase 1: count online healthy devices
            if (device.adb_connected is True
                    and device.adb_state not in ("offline", "unknown", "")):
                online_healthy_count += 1

            logger.info(f"device_adb_update: serial={serial}, adb_state={device.adb_state}, adb_connected={device.adb_connected}, network_latency={dev_data.get('network_latency')}")

            # Update hardware info (downsampled — connectivity always updates)
            write_hw = _should_write_hardware_snapshot(device, now)
            if write_hw:
                hardware_updated = False
                hardware_updated |= _update_if_not_none(device, "battery_level", dev_data.get("battery_level"))
                hardware_updated |= _update_if_not_none(device, "battery_temp", dev_data.get("battery_temp"))
                hardware_updated |= _update_if_not_none(device, "temperature", dev_data.get("temperature"))
                hardware_updated |= _update_if_not_none(device, "wifi_rssi", dev_data.get("wifi_rssi"))
                hardware_updated |= _update_if_not_none(device, "wifi_ssid", dev_data.get("wifi_ssid"))
                hardware_updated |= _update_if_not_none(device, "network_latency", dev_data.get("network_latency"))
                _update_if_not_none(device, "build_display_id", dev_data.get("build_display_id"))
                if hardware_updated:
                    device.hardware_updated_at = now

                # Update system resources (same downsample window)
                _update_if_not_none(device, "cpu_usage", dev_data.get("cpu_usage"))
                _update_if_not_none(device, "mem_total", dev_data.get("mem_total"))
                _update_if_not_none(device, "mem_used", dev_data.get("mem_used"))
                _update_if_not_none(device, "disk_total", dev_data.get("disk_total"))
                _update_if_not_none(device, "disk_used", dev_data.get("disk_used"))
            else:
                # Still accept build_display_id when first seen empty
                if not device.build_display_id:
                    _update_if_not_none(device, "build_display_id", dev_data.get("build_display_id"))

            # Update last_seen
            device.last_seen = now

            # Phase 6c: Business status — based on ADB connection and active lease
            # ADB 已发现设备但状态非 "device"（如 unauthorized）：设备物理在线但不可用，
            # 区别于纯粹未被发现的 OFFLINE，需要操作员介入（如重新授权调试）。
            if device.adb_state not in ("device", "offline", "unknown", "", None) and not device.adb_connected:
                device.status = "ERROR"
                logger.info(f"device_status_error: serial={serial}, adb_state={device.adb_state}")
            elif not device.adb_connected:
                device.status = "OFFLINE"
                logger.info(f"device_status_offline: serial={serial}, reason=adb_connected_false")
            elif device.id and device.id in busy_device_ids:
                device.status = "BUSY"
                logger.info(f"device_status_busy: serial={serial}, device_id={device.id}")
            else:
                device.status = "ONLINE"
                logger.info(f"device_status_online: serial={serial}, adb_connected=true, no_active_lease")

            ws_device_updates.append(
                {
                    "serial": device.serial,
                    "status": device.status,
                    "battery_level": device.battery_level,
                    "temperature": device.temperature,
                    "network_latency": device.network_latency,
                    "adb_state": device.adb_state,
                    "adb_connected": device.adb_connected,
                    "host_id": device.host_id,
                    "last_seen": device.last_seen.isoformat() if device.last_seen else None,
                }
            )

    # Mark missing devices as offline
    missing_devices = _mark_missing_devices_offline(db, host.id, seen_serials)
    for device in missing_devices:
        if device.serial in seen_serials:
            continue
        ws_device_updates.append(
            {
                "serial": device.serial,
                "status": device.status,
                "battery_level": device.battery_level,
                "temperature": device.temperature,
                "network_latency": device.network_latency,
                "adb_state": device.adb_state,
                "adb_connected": device.adb_connected,
                "host_id": device.host_id,
                "last_seen": device.last_seen.isoformat() if device.last_seen else None,
            }
        )

    db.commit()

    from backend.services.agent_version_gate import resolve_agent_min_version

    suggested_interval = _suggested_heartbeat_interval(online_healthy_count)
    suggested_log_rate = _suggested_log_rate_limit(online_healthy_count)
    return {
        "ok": True,
        "host_id": host.id,
        "devices_count": len(seen_serials),
        "script_catalog_outdated": script_catalog_outdated,
        # ADR-0019 Phase 3c
        "capacity": {
            "online_healthy_devices": online_healthy_count,
        },
        "agent_min_version": resolve_agent_min_version(),
        # ADR-0026 P0/P2-2: heartbeat + log-rate backpressure hints for Agent
        "backpressure": {
            "log_rate_limit": suggested_log_rate,
            "heartbeat_interval_seconds": suggested_interval,
        },
        "heartbeat_interval_seconds": suggested_interval,
    }, ws_device_updates
